export enum Tech {
  Javascript = "Javascript",
  Python = "Python",
  Java = "Java",
  PHP = "PHP",
  TypeScript = "TypeScript",
  SQLDatabases = "SQL Databases",
  NoSQLDatabases = "NoSQL Databases",
  APIs = "APIs",
  C = "C",
  HTMLCSS = "HTML & CSS",
  jQuery = "jQuery",
  Reactjs = "Reactjs",
  VueJs = "Vue.js",
  NextJs = "NextJs",
  Svelte = "Svelte",
  NodeJs = "Node.js",
  Django = "Django",
  Laravel = "Laravel",
  AWS = "AWS",
  Terraform = "Terraform",
  CICDPipelines = "CI / CD Pipelines",
  Grafana = "Grafana",
  Prometheus = "Prometheus",
  UnitTesting = "Unit Testing",
  ScrumAndAgileMethodologies = "Scrum and Agile Methodologies",
  Ansible = "Ansible",
  AI = "AI",
  Git = "Git",
  Microservices = "Microservices",
  DesignPatterns = "Design patterns",
  WebScraping = "Web Scraping",
  CloudTechnologies = "Cloud Technologies",
  Linux = "Linux",
  Docker = "Docker",
  Kubernetes = "Kubernetes",
}

export const tech_experience = [
  {
    title: "JavaScript",
    subheading:
      "(React, NextJs, VueJs, TypeScript, NodeJs, jQuery, HTML, CSS, Responsive Design)",
    description:
      "I have been working with JavaScript and web technologies (HTML/CSS) since 2018 and it is my go to language for frontend (React, NextJs, Vue) and back end (NodeJs, express) development. In recent years I am leaning more into TypeScript due to the predictability that comes with strictly typed software development.",
    rating: 4,
  },
  {
    title: "Amazon Web Services (AWS)",
    subheading: "(Cloud, EC2, VPC, EKS, S3, DynamoDB, IAM)",
    description:
      "I started using AWS in 2022 and in 2023 I achieved my AWS Cloud Practitioner and Solution Architect Associate Certifications. I understand the benefits that the cloud provides and can competently use AWS services to solve technical and business challenges and create scalable, reliable and cost effective applications.",
    rating: 3,
  },
  {
    title: "DevOps",
    subheading:
      "(CI / CD Pipelines, Alerting and Monitoring, Infrastructure as Code, Terraform, Deployment, Testing, github actions)",
    description:
      "I have used Git, BitBucket and GitHub for years and can proficiently use Version Control Systems (VCS) to collaborate with team members and used branching strategies like feature branches. I have created and worked with CI / CD Pipelines since 2020. Developed unit and end to end tests to ensure reliability of applications. At Builderscrack in 2022 I implemented an alerting and monitoring system with ansible, prometheus and grafana which alerted us to problems with our hosting provider. Recently I have achieved my HachiCorp Terraform Certification which I have used to deploy an EKS cluster to the AWS Cloud for my microservices project.",
    rating: 4,
  },
  {
    title: "Scrum, Agile and Workflows",
    subheading:
      "(Scrum, Agile, Stand Ups, Retrospectives, Code Reviews, Task Estimation)",
    description:
      "I started following scrum and agile methodologies in 2021 in University where I developed an application in a team of 8. This involved task estimation, stand ups, retrospectives, 2 week sprints and code reviews. During 2022 while at Builderscrack I developed these skills more contributing to standups and code reviews.",
    rating: 4,
  },
  {
    title: "Python",
    subheading: "(Scripting, Django, Data, AI, Genetic Algortihms) ",
    description:
      "Python is my go to tool for scripting, data processing and prototyping due to its simple syntax and ease of use. I have completed courses in Artificial Intelligence (AI), data structures and algorithms and compilers to name a few all in python. I regularly use python for web scraping, data collection and processing and computer vision with libraries like Pandas, Beautiful Soup and OpenCV.",
    rating: 4,
  },
  {
    title: "DataBases",
    subheading: "(SQL, MySQL, SQLite, MongoDB, MaraiaDB, DynamoDB, NoSQL)",
    description:
      "I have completed courses on Relational Databases and can confidently design efficient schemas, work with SQL to query tables and implement transactions. I have significant experience working with SQL and NoSQL databases (DynamoDB, MongoDB), locally and in the cloud and can confidently use these skills to store and manipulate data following industry best practices.",
    rating: 4,
  },
  {
    title: "Java",
    subheading: "(Spring, Maven, MVC, JUnit)",
    description:
      "Over 2021 I developed a single page application in a team of 8, where Java was used as the back end of the application. In 2024 I completed a course on Java development to strengthen my understanding and proficiency in the language.",
    rating: 3,
  },
  {
    title: "PHP",
    subheading: "(Laravel, MVC, PHP unit, Blade templates)",
    description:
      "During my time at Builderscrack I implemented features using PHP and the Laravel framework. The application followed a MVC architecture and I implemented frontend functionality with Blade templating.",
    rating: 3,
  },
  {
    title: "Containerisation",
    subheading: "(Docker, Kubernetes, Microservices, EKS)",
    description:
      "I can confidently use docker to containerise services and applications to ensure consistent application functionality and repeatability. I recently completed a course on developing applications using a microservice architecture which taught me about working with an event bus to communicate between services and how to solve concurrency issues in distributed systems. I then deployed this application to a Kubernetes cluster hosted on AWS.",
    rating: 4,
  },
];

export const Projects = [
  {
    name: "Microservices Ticketing App",
    tech: [
      Tech.Microservices,
      Tech.AWS,
      Tech.TypeScript,
      Tech.Javascript,
      Tech.NodeJs,
      Tech.Docker,
      Tech.Kubernetes,
      Tech.Git,
      Tech.CICDPipelines,
      Tech.UnitTesting,
      Tech.NextJs,
      Tech.Reactjs,
      Tech.HTMLCSS,
      Tech.NoSQLDatabases,
      Tech.SQLDatabases,
      Tech.Terraform,
    ],
    assets: [],
    date: "",
    problem:
      "How do you design an application that is scalable, reliable and available?",
    solution: "Microservices!",
    description:
      "This project showcases the extensive skills in DevOps and application architecture design developed through a Udemy course by Stephen Grider and enhanced by practical experience. It involves deploying a multi-region infrastructure on AWS EKS using Terraform to ensure the availability, reliability, and scalability of a ticket onselling site. The main focus of this project was architecture design, backend implementation and devops deoployment practices. It employs technologies like React, Next.js, Node.js, Express, and TypeScript, and utilizes Docker, Kubernetes, and CI/CD with GitHub Actions for deployment. Key features of the project include architecting scalable applications using microservices, managing concurrency in distributed systems, server-side rendering with React, and implementing robust security with JWT and cookies for user authentication. This framework has laid a solid foundation for future projects, aiming to streamline the development of scalable and reliable applications.",
  },
  {
    name: "Steam Marketplace Arbitrage",
    tech: [
      Tech.Javascript,
      Tech.NodeJs,
      Tech.AI,
      Tech.Docker,
      Tech.Python,
      Tech.DesignPatterns,
      Tech.Git,
      Tech.CloudTechnologies,
      Tech.AWS,
      Tech.NoSQLDatabases,
      Tech.WebScraping,
      Tech.APIs,
    ],
    assets: ["../src/public/trade-up.png"],
    date: "",
    description: "This is a test",
  },
  {
    name: "University Canteen Self Checkout System",
    tech: [
      Tech.Javascript,
      Tech.Python,
      Tech.Linux,
      Tech.HTMLCSS,
      Tech.CloudTechnologies,
      Tech.NoSQLDatabases,
    ],
    assets: ["../src/public/collegehousecanteen.png"],
    date: "",
    description: "This is a test",
  },
  {
    name: "Builderscrack",
    tech: [
      Tech.PHP,
      Tech.Laravel,
      Tech.Javascript,
      Tech.jQuery,
      Tech.HTMLCSS,
      Tech.Ansible,
      Tech.Grafana,
      Tech.Prometheus,
      Tech.Docker,
      Tech.Git,
      Tech.ScrumAndAgileMethodologies,
      Tech.NextJs,
      Tech.Python,
      Tech.UnitTesting,
      Tech.Linux,
      Tech.SQLDatabases,
      Tech.NoSQLDatabases,
      Tech.APIs,
    ],
    assets: ["../src/public/Builderscrack.png"],
    date: "",
    description: "This is a test",
  },
  {
    name: "Stock Portfolio Tracker",
    tech: [
      Tech.Django,
      Tech.Python,
      Tech.Git,
      Tech.HTMLCSS,
      Tech.Reactjs,
      Tech.Javascript,
      Tech.SQLDatabases,
      Tech.APIs,
    ],
    assets: ["./src/public/stockportfolio.png"],
    date: "",
    description: "This is a test",
  },
  {
    name: "Portfolio Site (You're on it!)",
    tech: [
      Tech.Svelte,
      Tech.HTMLCSS,
      Tech.Javascript,
      Tech.AWS,
      Tech.TypeScript,
      Tech.Git,
    ],
    assets: [],
    date: "",
    description: "This is a test",
  },
  {
    name: "Uber Carshare Data Insights",
    tech: [
      Tech.Python,
      Tech.AWS,
      Tech.Linux,
      Tech.Git,
      Tech.SQLDatabases,
      Tech.WebScraping,
    ],
    assets: [],
    date: "",
    description: "This is a test",
  },
  {
    name: "GPT Recruiter",
    tech: [
      Tech.Python,
      Tech.WebScraping,
      Tech.Git,
      Tech.SQLDatabases,
      Tech.AI,
      Tech.APIs,
    ],
    assets: [],
    date: "",
    description: "This is a test",
  },
  {
    name: "Software Engineering Group Project",
    tech: [
      Tech.Java,
      Tech.VueJs,
      Tech.Git,
      Tech.SQLDatabases,
      Tech.CICDPipelines,
      Tech.ScrumAndAgileMethodologies,
      Tech.HTMLCSS,
      Tech.Javascript,
      Tech.UnitTesting,
      Tech.APIs,
    ],
    assets: [],
    date: "",
    description: "This is a test",
  },
  {
    name: "Executable to Image Encoder and Decoder",
    tech: [Tech.Javascript],
    assets: [],
    date: "",
    description: "This is a test",
  },
  {
    name: "Computer Vision Gameplay Editor",
    tech: [Tech.Python, Tech.AI],
    assets: ["./src/public/csgo-scout-ace.mp4"],
    problem:
      "The native game resoulution is not mobile friendly for youtube videos and it takes too long to edit",
    solution:
      "Use computer vision to extract important information and automate parts of the editing process",
    date: "",
    description:
      "Youtube Shorts and shortform video mobile platforms like tiktok have huge viewerbases especially in the gaming niche for gameplay highlights. Due to the vertical video format of ",
  },
  {
    name: "AWS AdBlocker and Youtube Downloader",
    tech: [Tech.AWS, Tech.CloudTechnologies, Tech.Python],
    assets: [],
    problem: "I don't want Youtube ads",
    solution:
      "Use a custom DNS to block ads and SSL termination to intercept the video and stream it back to the client without ads",
    date: "",
    description: "This is a test",
  },
  {
    name: "Micro-controller Multiplayer Tetris Game",
    tech: [Tech.Git, Tech.C],
    assets: [],
    date: "2019",
    description: "This is a test",
  },
];
